apps/user/urls.py
from django.urls import include, path, re_path
from apps.user import views

app_name = 'user'

wishlist = [
    path('',        views.WishlistViewsSet.as_view({'get': 'data'}),    name='wishlist'),
    path('add/',    views.WishlistViewsSet.as_view({'post': 'add'}),    name='wishlist_add'),
    path('remove/', views.WishlistViewsSet.as_view({'post': 'remove'}), name='wishlist_remove'),
]

authentication = [
    path('',  views.AuthenticationView.as_view(), name='authentication'),
    re_path(
        r"^(?P<page>login|registration|)/?((?P<api>api)/)?$", 
        views.AuthenticationView.as_view(), 
        name='authentication'
    ),
]

profile = [
    path('', views.ProfileViewsSet.as_view({'get': 'user_data'}), name='user_data'),
    path('orders/', views.ProfileViewsSet.as_view({'get': 'user_orders'}), name='user_orders'),
]

urlpatterns = [
    path('whishlist/',  include(wishlist)),
    path('authntication/', include(authentication)),
    path('profile/', include(profile)),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, path, include
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.catalogue.urls')),
    path('documents', include('apps.documents.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

templates/shop/additions/whishlist/wishlist.html
{% load static %}<div class="side_wishlist side_popup popup ">
    <div class="head">
        <p class="h4 title">Список желаний</p>
        <div class="close" onclick="closeCart()">
            <img class="close_img" src="{% static 'img/close.png' %}" alt="x">
        </div>
    </div>
    <div class="body">
       {% include 'shop/additions/whishlist/wishlist__body.html' %}
    </div>
    
</div>

templates/shop/additions/whishlist/wishlist__body.html
{% if request.user.is_authenticated %}
    {% with products=request.user.products.all %}
        {% if products|length %}
            <div class="wishlist_products">
                {% for product in request.user.products.all %}
                    {% include 'shop/additions/whishlist/wishlist__product.html' %}
                {% endfor %}
            </div>
        {% else %}
            <p>Пока вы ничего не добавили в список желаний</p>
        {% endif %}
    {% endwith %}
{% else %}
<div class="auth_message">
    <p class="text">Необходимо авторизоваться для того чтоб добавлять в список желаний</p>
    <a class="btn-md login" href="">Вход в личный кабинет</a>
    <a class="btn-md register" href="">Еще не зарегестрированы?</a>
</div>
{% endif %}

templates/shop/additions/whishlist/wishlist__product.html
{% load static %}

{% with product=product.product %}
<div class="catalogue__product">
    <div class="image">
        <a href="{{ product.product.get_absolute_url }}">
            <img src="{{ product.images.all.0.image_thmb.l.path }}" alt="">
        </a>
    </div>
    <div class="info">
        <p class="name">{{ product.name }}</p>
        <div class="shop">
            <div class="buy">
                <div class="price">
                    {% if product.get_price_old_ua > product.get_price_ua %}
                        <p class="old_price">{{ product.get_price_old_ua }} грн.</p>
                    {% endif %}
                    <p class="current_price">{{ product.get_price_ua }} грн.</p>
                </div>
                <button onclick="CartAddID('{{ product.id }}')">Купить</button>
            </div>
            <form action="{% url 'user:wishlist_remove' %}" method="POST" class="remove_from_wishlist">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <button class="action">
                    <img src="{% static 'img/icons/heart-red.png' %}" alt="like">
                </button>
            </form>
            
            <button class="action">
                <img src="{% static 'img/icons/compare-grey.png' %}" alt="compare">
            </button>
        
        </div>
    </div>
</div>
{% endwith %}