apps/documents/urls.py
from django.urls import include, path, re_path
from apps.documents import views


app_name = 'documents'


cart = [
    path('add-update', views.CartAddUpdate, name='cart-add-update'),
    path('delete',     views.CartDelete,    name='cart-delete'),
    path('clear',      views.CartClear,     name='cart-clear'),
]

invoice = [
    path('update/',           views.InvoiceUpdate,  name='invoice-update'),
    path('update/<int:id>/',  views.InvoiceUpdate,  name='invoice-update'),
    path('get/',              views.InvoiceGet,    name='invoice-get'),
    path('get/<int:id>/',     views.InvoiceGet,    name='invoice-get'),
    path('print/',            views.InvoicePrint,  name='invoice-print'),
    path('print/<int:id>/',   views.InvoicePrint,  name='invoice-print'),
    # path('product-delete/<invoice>/<product>',   views.InvoiceProductDelete,  name='invoice-product-delete'),
    
]


urlpatterns = [
    path('invoice/',  include(invoice)),
    path('cart/',     include(cart))
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, path, include
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.catalogue.urls')),
    path('documents', include('apps.documents.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

templates/database/invoice/form.html
{% load static %}


<div class="popup__outer" id="invoice__popup">
    <div class="popup__conteiner">
        <span class="close" onclick="Close('invoice__popup')">
            <img src="{% static 'img/close.png' %}" alt="x">
        </span>
        <div class="popup__wrapper invoice container" id="invoice_form">
            <div class="preloader">loading...</div>
        </div>
    </div>
</div>

{% include 'database/invoice/tpl/tpl_invoice.html' %}



<script>
    const urlInvoiceUpdate = "{% url 'documents:invoice-update' %}"
    const urlInvoicePrint = "{% url 'documents:invoice-print' %}"
    const urlInvoiceGet = "{% url 'documents:invoice-get' %}"
</script>