apps/catalogue/urls.py
from django.urls import re_path, path, include
from apps.catalogue import views

app_name = 'catalogue'


urlpatterns = [
    path('', views.catalogue, name="catalogue"),
    re_path(r'^(?P<size>small|middle|big|clean)/$', views.catalogue, name="whoosale"),
    path('export_excel/', views.export_excel, name="export_excel"),
    # re_path(r'^export_excel/(?P<price>\w+)?(/(?P<whoosale>small|middle|big)?)?', views.export_excel, name="export_excel"),
    path('product/<id>/', views.product, name="product"),
   
    path('products_zip/', views.products_zip, name="products_zip"),
    path('products_zip/<ids>', views.products_zip, name="products_zip"),
]


apps/shop/urls.py
from django.urls import re_path, path, include
from apps.shop import views

app_name = 'shop'


urlpatterns = [
    path('', views.home, name="home"),
    path('watchlist', views.watchlist, name="watchlist"),
    re_path(
        r'''^catalogue/(?P<category>[\w-]+)/?(?:\/(?P<sort>price_asc|price_dsc|newest|popularity)/)?'''
        # r'''?(sort-by-(?P<sort>price_asc|price_dsc|newest|popularity))?/'''
        r'''?(?:\/filter/(?P<atributes>[-=,\w/]*))?$''',
        views.Catalogue.as_view(), 
        name="catalogue"
    ),
    re_path(
        r'''^catalogue/(?P<category>[\w-]+)/product-(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)/'''
        r'''?(?:\/(?P<page>characteristics|comments|questions|certificates|))?/?$''',
        views.ProductPage.as_view({'get':'page'}), 
        name="product"
    ),
    re_path(
        r'''^catalogue/(?P<category>[\w-]+)/product-(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)/'''
        r'''?(?:\/(?P<page>comment_form))?/?$''',
        views.ProductPage.as_view({'post':'comment_form'}), 
        name="comment_form"
    ),
     re_path(
        r'''^catalogue/(?P<category>[\w-]+)/product-(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)/'''
        r'''?(?:\/(?P<page>question_form))?/?$''',
        views.ProductPage.as_view({'post':'question_form'}), 
        name="question_form"
    ),



    
]


apps/user/urls.py
from django.urls import include, path, re_path
from apps.user import views

app_name = 'user'

wishlist = [
    path('',        views.WishlistViewsSet.as_view({'get': 'data'}),    name='wishlist'),
    path('add/',    views.WishlistViewsSet.as_view({'post': 'add'}),    name='wishlist_add'),
    path('remove/', views.WishlistViewsSet.as_view({'post': 'remove'}), name='wishlist_remove'),
]

authentication = [
    path('',  views.AuthenticationView.as_view(), name='authentication'),
    re_path(
        r"^(?P<page>login|registration|)/?((?P<api>api)/)?$", 
        views.AuthenticationView.as_view(), 
        name='authentication'
    ),
]

profile = [
    path('', views.ProfileViewsSet.as_view({'get': 'user_data'}), name='user_data'),
    path('orders/', views.ProfileViewsSet.as_view({'get': 'user_orders'}), name='user_orders'),
]

urlpatterns = [
    path('whishlist/',  include(wishlist)),
    path('authntication/', include(authentication)),
    path('profile/', include(profile)),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, path, include
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.catalogue.urls')),
    path('documents', include('apps.documents.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

apps/catalogue/models/models__category.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from apps.core.models import NameSlug
from apps.catalogue_filters.models import *
from project import settings 
from apps.core.models import Translation
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel, TreeForeignKey
import datetime, unidecode



class Category(NameSlug, Translation, MPTTModel):
    parent =        TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    # RETAIL
    price =         models.DecimalField(default=1.25, decimal_places=2, max_digits=200, verbose_name='Наценка, розница') 
    # SMALL WHOOSALE
    sm_price =      models.DecimalField(default=1.10, decimal_places=2, max_digits=200, verbose_name='Наценка, мелкий опт') 
    sm_start =      models.PositiveIntegerField(blank=True, default=10, verbose_name='Начало малого опта')
    # MIDDLE WHOOSALE
    md_price =      models.DecimalField(default=1.05, decimal_places=2, max_digits=200, verbose_name='Наценка, средний опт') 
    md_start =      models.PositiveIntegerField(blank=True, default=20, verbose_name='Начало среднгего опта')
    # BIG WHOOSALE
    bg_price =      models.DecimalField(default=1.00, decimal_places=2, max_digits=200, verbose_name='Наценка, крупный опт') 
    bg_start =      models.PositiveIntegerField(blank=True, default=40, verbose_name='Начало большого опта')
    ignore_multiply = models.BooleanField(default=False, verbose_name='Без наценки')
    description = RichTextField(blank=True, verbose_name='Описание')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    class MPTTMeta:
        order_insertion_by = ['name']

    def get_slug(self):
        slug = slugify(unidecode.unidecode(self.name))
        return slug

    @property
    def products_count(self):
        from apps.catalogue.models.models__product import Product
        return Product.objects.filter(category__in=self.get_descendants(include_self=True)).distinct().count()

    def get_absolute_url(self):
        return reverse('shop:catalogue', kwargs={'category' : self.slug})

apps/shop/models.py
from django.db import models

# Create your models here.

apps/catalogue_filters/forms.py
from django import forms


class CategoryAttributeValueForm(forms.ModelForm):
    model = 'catalogue_filters.CategoryAttributeValue'

    class Meta:
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryAttributeValueForm, self).__init__(*args, **kwargs)
        if 'instance' in kwargs.keys():
            print(kwargs)
            if kwargs['instance'] is not None:
                pass
                # categories = []
                # category = kwargs['instance'].category
                # while category != None:
                #     categories.append(category)
                #     category = category.parent
                # self.fields['selection'].queryset = Selection.objects.filter(parent__in=categories)

apps/catalogue/views.py
from project import settings
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.db.models import Q, Prefetch, Case, When, IntegerField, Count
from django.db import connection
from django.utils.html import escape
from django.utils.translation import gettext as _
from django.utils.text import slugify
from django.utils.translation import get_language as lang
from django.template.defaultfilters import slugify
from django.views.decorators.csrf import csrf_exempt
# APPS
from apps.core.functions.serializer import getSerializerLabels
from apps.catalogue_filters.models import Attribute, AttributeValue, CategoryAttribute, CategoryAttributeValue, ProductAttribute
from apps.catalogue.serilaizers import CategorySerializer, AttributeSerializer, AttributeValueSerializer, ProductSerializer
from apps.documents.models import Product, Category, PriceFormula, Invoice, InvoiceTemplate
from apps.documents.serializers import InvoiceSerializer
# Django rest framework
from rest_framework import routers, serializers, viewsets
from rest_framework.fields import SerializerMethodField
# libs
from io import BytesIO
from decimal import *
from unidecode import unidecode
from datetime import datetime


#  glob Libs
import json, io, xlsxwriter, zipfile, os



@csrf_exempt
def catalogue(request, *args, **kwargs):
    filters = ['categories', 'atributes']
    params = {}
    for fltr in filters:
        value = request.GET.get(fltr)
        if value != None and len(value) > 0:
            params[fltr] = [int(pk) for pk in value.split(',')]
        else: params[fltr] = []

    # Categories
    categoryQP = {}
    if params['categories']:
        categoryQP['pk__in'] = params['categories']
    categories = Category.objects.filter(**categoryQP)

    category = CategorySerializer(categories.first()).data


    # Attributes
    attr_values = AttributeValue.objects.distinct().filter(
        category_values__parent__parent__in = categories,
        product_attrs__parent__category__in = categories,
    )
    attrs = Attribute.objects.distinct().filter(values__in=attr_values)

    count = Count('book', filter=Q(book__rating__gt=5))
    
    
    # Serializers
    attrContext = {
        'attr_values' : attr_values,
        'selected' : params['atributes'],
    }

    attributes = json.loads(json.dumps(AttributeSerializer(attrs, many=True, context=attrContext).data))
    
    args = {
        'attributes' : attributes,
        'categories' : Category.objects.all(),
        'formulas' : PriceFormula.objects.all(),
        'invoices' : Invoice.objects.all(),
        'invoice_templates' : InvoiceTemplate.objects.all(),
       
        # 'context' : context
    }

    if 'size' in kwargs.keys():
        args['size'] = kwargs['size']

    if request.method == 'POST':
        products = Product.objects.all()
        if params['categories']:
            products = products.filter(category__pk__in = params['categories'])

        if params['atributes']:
            atributes = Attribute.objects.distinct().filter(values__in=params['atributes'])
            for attr in atributes:
                products = products.distinct().filter(product_attrs__attribute__attribute__pk = attr.pk, product_attrs__value__pk__in = params['atributes'])
        
        # attr_values
        count = Count('product_attrs', filter=Q(product_attrs__parent__pk__in=products.values_list('pk', flat=True)), distinct=True)
        
        for attr in attrs:
            attr.values.annotate(count=count)
            
            # for value in attr.entry_set.all():
            #     print(value)
            # for value in attr.values.all():
            #     print(value.count)
       
            # products = Product.objects.distinct().filter(category__pk__in = params['categories']).order_by('category','-has_price','code')

        productSerializer = ProductSerializer(products, many=True, context={'whoosale' : kwargs['size'] if 'size' in kwargs.keys() else None })
        productsLabels = getSerializerLabels(ProductSerializer())
        products =  json.loads(json.dumps(productSerializer.data))
    
        response = {
            'products' : products,
            'attributes' : attributes,
            'category' : category
            # 'context' : context,
        }
        dump = json.dumps(response)
        return JsonResponse(dump, content_type='application/json', safe=False)
    else:
        return render(request, 'database/catalogue.html', args)

@csrf_exempt
def product(request, id):
    args = {}
    args['product'] = Product.objects.get(pk=id)
    return render(request, 'database/product/product.html', args)



@csrf_exempt
def export_excel(request, *args, **kwargs):
    output = io.BytesIO()
    print(request.GET.get('products'))
    
    if 'products' in request.GET:
        productsIDs = [int(id) for id in request.GET.get('products').split(',')]
        products = Product.objects.filter(pk__in=productsIDs)
    else:
        products = Product.objects.all()
   


    if 'price' in request.GET:
        priceFormula = PriceFormula.objects.get(pk=int(request.GET.get('price'))).formula
    else: priceFormula = 'x'
   
    workbook = xlsxwriter.Workbook(output)
    ws = workbook.add_worksheet()

    priceFormat = {'num_format': '$#,##0.00'}

    data = [
        { 'title' : '№',                                 'width' : 8,  'attr' : 'num'},
        { 'title' : _('Изображение'),                    'width' : 23, 'attr' : 'image'},
        { 'title' : _('Артикул'),                        'width' : 16, 'attr' : 'code'},
        { 'title' : _('Название продукции'),             'width' : 32, 'attr' : 'name'},
        { 'title' : _('Категория'),                      'width' : 32, 'attr' : 'get_category'},
        { 'title' : _('Тип'),                            'width' : 16, 'attr' : 'get_type'},

        # { 'title' : _('Цена'),                           'width' : 16, 'attr' : 'price',        'format' : {'num_format': '$#,##0.00'}},
        
      
        { 'title' : _('Производитель'),                  'width' : 24, 'attr' : 'manufacturer'},
        # { 'title' : _('Время поставки'),                 'width' : 24, 'attr' : 'get_delivery_time','format' : {'num_format': '[$-x-sysdate]dddd, mmmm dd, yyyy'}},
        { 'title' : _('W'),                              'width' : 4,  'attr' : 'box_w'},
        { 'title' : _('L'),                              'width' : 4,  'attr' : 'box_l'},
        { 'title' : _('H'),                              'width' : 4,  'attr' : 'box_h'},
        { 'title' : _('Обьем'),                          'width' : 12, 'attr' : 'get_volume', 'format' : {'num_format': '#,####0.0000'}},
        { 'title' : _('Обьемный вес'),                   'width' : 12, 'attr' : 'get_volume_weight', 'format' : {'num_format': '#,##0.00'}},
        { 'title' : _('Вес брутто'),                     'width' : 12, 'attr' : 'weight_brutto'},
        { 'title' : _('Вес доставки'),                   'width' : 12, 'attr' : 'weight_delivery'},
        { 'title' : _('Штук в ящике'),                   'width' : 12, 'attr' : 'pieces_in_box'},
        
        # { 'title' : _('Цена с доставкой в Киеве, шт'),   'width' : 24, 'value' : '=Q#+F#', 'format' : {'num_format': '$#,##0.00'}},
        # { 'title' : _('Цена с доставкой в Киеве, ящик'), 'width' : 24, 'value' : '=R#*P#', 'format' : {'num_format': '$#,##0.00'}},
        # { 'title' : _('Ссылка на документы'),            'width' : 48, 'attr' : 'link'},
    ] 
    

    if 'whoosale' not in request.GET:
        whoosale = [
            { 'title' : _('Цена'),                           'width' : 16, 'attr' : 'price',        'format' : {'num_format': '$#,##0.00'}},
            { 'title' : _('Мелкий опт'),                     'width' : 16, 'attr' : 'get_sm_price', 'format' : {'bg_color':'deeaff', 'num_format': '$#,##0.00'}},
            { 'title' : _('Цена с доставкой'),               'width' : 16, 'value' : '=H#+Z#',      'format' : {'bg_color':'deeaff', 'num_format': '$#,##0.00'}},
            { 'title' : _('мин. партия'),                    'width' : 16, 'attr' : 'pieces_in_box', 'format' : {'bg_color':'deeaff'}},
            { 'title' : _('Средний опт'),                    'width' : 16, 'attr' : 'get_md_price', 'format' : {'bg_color':'c7dcff', 'num_format': '$#,##0.00'}},
            { 'title' : _('Цена с доставкой'),               'width' : 16, 'value' : '=K#+Z#',      'format' : {'bg_color':'c7dcff', 'num_format': '$#,##0.00'}},
            { 'title' : _('мин. партия'),                    'width' : 16, 'attr' : 'get_md_start', 'format' : {'bg_color':'c7dcff'}},
            { 'title' : _('Крупный опт'),                    'width' : 16, 'attr' : 'get_bg_price', 'format' : {'bg_color':'bdd5ff', 'num_format': '$#,##0.00'}},
            { 'title' : _('Цена с доставкой'),               'width' : 16, 'value' : '=N#+Z#',      'format' : {'bg_color':'bdd5ff', 'num_format': '$#,##0.00'}},
            { 'title' : _('мин. партия'),                    'width' : 16, 'attr' : 'get_bg_start', 'format' : {'bg_color':'bdd5ff'}},
        ]
        delivery = [{ 'title' : _('Цена доставки 1 шт'),      'width' : 24, 'value' : '=X#/Y#*10', 'format' : {'num_format': '$#,##0.00'}}]
       
    else:
        if request.GET.get('whoosale') == 'big':
            whoosale = [
                { 'title' : _('Крупный опт'),                    'width' : 16, 'attr' : 'get_bg_price', 'format' : {'bg_color':'bdd5ff', 'num_format': '$#,##0.00'}},
                { 'title' : _('Цена с достаыкой'),               'width' : 16, 'value' : '=G#+S#',      'format' : {'bg_color':'bdd5ff', 'num_format': '$#,##0.00'}},
                { 'title' : _('мин. партия'),                    'width' : 16, 'attr' : 'get_bg_start', 'format' : {'bg_color':'bdd5ff'}},]
            
        elif request.GET.get('whoosale') == 'middle':
            whoosale = [

apps/shop/views/views__home.py
from django.shortcuts import render


def home(request):
    return render(request, 'shop/home/home.html')

apps/shop/views/views__watchlist.py
from django.shortcuts import render
from django.template.loader import render_to_string
from apps.shop.watchlist import WatchList
from django.http import JsonResponse
import json

def watchlist(request):
    watchlist = WatchList(request)
    
    template = 'shop/additions/watchlist/watchlist__products.html'
    html = render_to_string(template, {'products' : watchlist.data()})
    return JsonResponse({'html' : html, 'length' : len(watchlist.data())})

templates/shop/catalogue/catalogue.html
{% extends 'shop/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/shop/catalogue/catalogue.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop/catalogue/catalogue__pricerange.css' %}">
{% endblock %}

{% block content %}
<div class="content">
    <!-- BREADCRUMBS -->
    <div class="breadcrumbs">
        <a href="/">
            <img src="{% static 'img/icons/home.png' %}" alt="home-page">
        </a>
        <span class="slash">/</span>
        {% for c in category.get_ancestors %}
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            <span class="slash">/</span>
        {% endfor %}
        <a href="{% url 'shop:catalogue' category=category.slug %}">{{ category.name }}</a>    
    </div>

    <!-- TITLE -->
    <p class="hdng">
        {% if not category %}Каталог{% else %}{{ category.name }} 
        <span>({{ category.products_count }})</span>{% endif %}
    </p>


    <div class="catalogue">
        <div class="filters">
            {% include 'shop/catalogue/catalogue__filters.html' %}
        </div>
        <div class="products">
            {% if category.get_children|length %}
                <ul class="categories">
                    {% for c in category.get_children %}
                        {% if c.products_count > 0 %}
                            <a href="{{ c.get_absolute_url }}">
                                <li>{{ c.name }} ({{c.products_count}})</li>
                            </a>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="sort">
                <select data-changed=false name="sort" id="">
                    <option value="new" selected=true>Новинки</option>
                    <option value="new">Популярные</option>
                    <option value="price__gte">Цене по возрастанию</option>
                    <option value="price__lte">Цене по убыванию</option>
                </select>
                <select data-changed=false name="show" id="">
                    <option selected=true value="24">24</option>
                    <option value="48">48</option>
                    <option value="96">96</option>
                </select>

                <ul class="view">
                    <li class="column"></li>
                    <li class="grid"></li>
                </ul>
                
            </div>
            {% include 'shop/catalogue/catalogue__product__list.html' %}
        </div>
    </div>
</div>



{% endblock %}

{% block js %}
<script async src="{% static 'js/shop/catalogue/pricerange.js' %}"></script>
<script>
    var url = "{% url 'shop:catalogue' category=category.slug %}"
    var priceRangeDiv =    document.querySelector('.price-slider')
    var filterParams =     document.querySelectorAll('.filter-param')

   
    function setPriceRange() {
        priceRangeDiv.dataset.changed = true
        priceRangeDiv.dataset.from = priceRangeDiv.querySelector('.from').value
        priceRangeDiv.dataset.to =   priceRangeDiv.querySelector('.to').value
    }


    function getQueryParams() {
        let queryParams = {}
        let from = priceRangeDiv.querySelector('.from') 
        let to = priceRangeDiv.querySelector('.to') 
        if (from.value != from.min || to.value != to.max) {
            queryParams['price'] = [priceRangeDiv.dataset.from, priceRangeDiv.dataset.to]
        }
        // if (priceRangeDiv != undefined && priceRangeDiv.dataset.changed == "true") {
           
        // }
        for (let input of filterParams) {
            if (input.checked) {
                let group = input.dataset.group
                let value = input.dataset.value
                if(queryParams[group] == undefined) {
                    queryParams[group] = [value]
                } else {
                    queryParams[group].push(value)
                }
            }
        }
        return queryParams
    }


    function createUrlParams(queryParams) {
        let params = ''
        for (let group in queryParams) {
            params += group + '=' + queryParams[group].join(',') + '/'
        }
        return params
    } 


    function cataloguePostRequest(params) {
        if (params.length > 0) {
            window.location.href = url + '/filter/' + params
        } else {
            window.location.href = url
        }
    }

        
    for (let input of document.querySelectorAll('.price_range, .filter-param')) {
        input.onchange = () => { 
            if (input.classList.contains('price_range')) {
                setPriceRange()
            }
            let queryParams = getQueryParams()
            let params = createUrlParams(queryParams)
            cataloguePostRequest(params) 
        }
    }

    
    
   

    


</script>
{% endblock %}

templates/shop/catalogue/catalogue__filters.html

<div class="block price {% if min_price == max_price %}deactivated{% endif %}">
    <div class="title">Цена</div>
    <div class="data">
        {% include 'shop/catalogue/catalogue__pricerange.html' %}
    </div>
</div>

{% for attr in attributes %}
    <div class="block">
        <div class="title">{{ attr.name }}</div>
        <div class="data">
            {% for value in attr.values %}
                    <li>
                        <label class="ml8" for="attr-{{ value.pk }}">
                            <input 
                                type="checkbox" 
                                class="filter-param" 
                                id="attr-{{ value.pk }}"
                                data-group="{{ attr.slug }}"  
                                data-value="{{ value.slug }}" 
                                {% if value.selected %}
                                    checked=true
                                {% endif %}
                            >
                            <span class="checkbox"></span>
                            <p>
                                <span>{{ value.name }} </span>
                                <span class="qty filterd">{% if value.count.filterd > 0 %}({{ value.count.filterd }}){% endif %}</span> 
                                <span class="qty extra">{% if value.count.extra > 0 %}+{{ value.count.extra }}{% endif %}</span> 
                            </p>
                        </label>
                    </li>
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/shop/catalogue/catalogue__pricerange.html
<div 
    class="price-slider" 
    data-changed="{% if price__gte > min_price or price__lte < max_price %}true{% else %}false{% endif %}"
    data-from="{{ price__gte }}" 
    data-to="{{ price__lte }}">
    <span>
        <span>От</span>
        <input class="price_range from" type="number" value="{{ price__gte }}" min="{{ min_price }}" max="{{ max_price }}"/>
        <span>до</span>
        <input class="price_range to"   type="number" value="{{ price__lte }}" min="{{ min_price }}" max="{{ max_price }}"/>
    </span>
    <input class="price_range from" value="{{ price__gte }}"  min="{{ min_price }}" max="{{ max_price }}" step="1" type="range"/>
    <input class="price_range to"   value="{{ price__lte }}"  min="{{ min_price }}" max="{{ max_price }}" step="1" type="range"/>
</div>
{% if min_price != max_price %}
<ul class="scale">
    
    <li><p>{{ min_price }}</p></li>
        
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    <li><p>{{ max_price }}</p></li>
    
</ul>
{% endif %}

templates/shop/catalogue/catalogue__product.html
{% load static %}
<div class="catalogue__product">
    <div class="image">
        <a href="{{ product.get_absolute_url }}">
            <img src="{{ product.images.all.0.image_thmb.l.path }}" alt="">
        </a>
    </div>
    <div class="info">
        <div class="top">
            {% if product.reviews.all|length %}
                <div class="reviews">
                    <div class="stars">
                        <img src="{% static 'img/icons/star.png' %}" alt="*">
                        <img src="{% static 'img/icons/star.png' %}" alt="*">
                        <img src="{% static 'img/icons/star.png' %}" alt="*">
                        <img src="{% static 'img/icons/star.png' %}" alt="*">
                        <img src="{% static 'img/icons/star.png' %}" alt="*">
                    </div>
                    <p>3 отзыва</p>
                </div>
            {% endif %}
            <p class="code">код: <span>{{ product.code }}</span></p>
            
        </div>
        <p class="name">{{ product.name }}</p>
        <div class="shop">
            <div class="buy">
                <div class="price">
                    {% if product.get_price_old_ua > product.get_price_ua %}
                        <p class="old_price">{{ product.get_price_old_ua }} грн.</p>
                    {% endif %}
                    <p class="current_price">{{ product.get_price_ua }} грн.</p>
                </div>
                <button>Купить</button>
            </div>
            
            <form action="{% url 'user:wishlist_add' %}" method="POST" class="add_to_wishlist">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <button><img src="{% static 'img/icons/heart-grey.png' %}" alt=""></button>
            </form>
            <form action="" method="POST" >
                {% csrf_token %}
                <input type="hidden" name="product_id">
                <button><img src="{% static 'img/icons/compare-grey.png' %}" alt=""></button>
            </form>
        
        </div>
    </div>
</div>

templates/shop/catalogue/catalogue__product__list.html
<div class="products__list">
    {% for product in products %}
            {% include 'shop/catalogue/catalogue__product.html' %}
    {% endfor %}
</div>